### PR TITLE
Pipeline ✨

### PR DESCRIPTION
**Pull request by molvrr**
## Solution
This PR sets up a pipeline with the following code quality tools:
- Rubocop
- RSpec

Thanks to job summaries we now have a rubocop report at the end of every job execution. I'm also adding RubyCritic, but for now it won't run on the pipeline

## Related links
- [Rubocop](https://github.com/rubocop/rubocop)
- [Rubycritic](https://github.com/whitesmith/rubycritic)
- [Github Actions Job Summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/)

### CODE REVIEW

**Comment by hikari-luz** [comment]
:rocket:  LGTM :rocket:

**Review by hikari-luz — APPROVED** [review]
LreallyGTM :rocket: :rocket: :rocket:

**Review by AllanSiqueira — APPROVED** [review]
:rocket:

**Review by Hikari-desuyoo — APPROVED** [review]
LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Pull request merged**
